import { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  // 示例：数据获取逻辑
  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await fetch('/api/data');
        const json = await res.json();
        setData(json);
      } catch (error) {
        console.error('数据获取失败:', error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js 项目首页</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          欢迎使用 <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {loading ? (
          <p>加载中...</p>
        ) : (
          <div className={styles.grid}>
            {data?.map((item) => (
              <div key={item.id} className={styles.card}>
                <h2>{item.title}</h2>
                <p>{item.description}</p>
              </div>
            ))}
          </div>
        )}

        <div className={styles.footer}>
          <Link href="/about" legacyBehavior>
            <a>关于我们 →</a>
          </Link>
        </div>
      </main>
    </div>
  );
}

// 服务端数据预取（可选）
export async function getStaticProps() {
  // 示例：从API或数据库获取数据
  const mockData = [
    { id: 1, title: '示例项目1', description: '这是第一个示例项目' },
    { id: 2, title: '示例项目2', description: '这是第二个示例项目' },
  ];

  return {
    props: {
      fallbackData: mockData, // 传递给页面的初始数据
    },
  };
    }
